name: humps
version: 0.1.0
description: Convert camelCase to underscore_separated and vice versa.
#homepage: https://sparkcentral.com
#author: Sparkcentral Engineering <dev@sparkcentral.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: "^0.12.6+1"
